"""AI agent that turns aggregated shift risk data into an executive passdown summary.

Default is a deterministic rule-based narrative generator (no external calls).
If LLM_PROVIDER is set to `openai` or `azure` and credentials are present, the
narrative section is generated by the model, with automatic fallback to rules.
"""

from __future__ import annotations

import html
import logging
import re
from datetime import datetime
from typing import Any

import httpx

from .config import settings

log = logging.getLogger(__name__)

SYSTEM_PROMPT = (
    "You are a manufacturing shift risk analyst. Given structured shift risk data, "
    "write a concise executive passdown: 3-6 bullet points covering the highest "
    "risks, their business impact, what the next shift must action first, and any "
    "escalation needed. Be specific, use the numbers provided, no preamble, no "
    "markdown headers. Plain bullet lines starting with '- '."
)


def _rule_narrative(shift: str, agg: dict[str, Any]) -> list[str]:
    bullets: list[str] = []
    crit = agg["by_band"].get("Critical", 0)
    high = agg["by_band"].get("High", 0)

    if agg["total"] == 0:
        return [f"No risks recorded for Shift {shift}. Clean handover — no open actions."]

    posture = (
        "ESCALATION REQUIRED" if crit else
        "ELEVATED" if high else
        "STABLE"
    )
    bullets.append(
        f"Shift {shift} risk posture is {posture}: {agg['open']} open risks "
        f"({crit} critical, {high} high), average risk score {agg['avg_score']}/100, "
        f"shift health index {agg['health']}/100."
    )

    for r in agg["critical"][:3]:
        bullets.append(
            f"CRITICAL — {r['title']} ({r['area']}, owner {r['owner'] or 'unassigned'}): "
            f"score {r['score']}, severity {r['severity']}/5, likelihood {r['likelihood']}/5, "
            f"{r['downtime_minutes']:.0f} min downtime exposure. "
            f"Next action: {r['action'] or 'assign owner and define containment'}."
        )

    if not agg["critical"]:
        for r in agg["top"][:2]:
            bullets.append(
                f"{r['band'].upper()} — {r['title']} ({r['area']}): score {r['score']}, "
                f"owner {r['owner'] or 'unassigned'}. "
                f"Next action: {r['action'] or 'review and confirm mitigation'}."
            )

    if agg["by_area"]:
        top_area, count = next(iter(agg["by_area"].items()))
        bullets.append(
            f"Risk concentration in {top_area} ({count} of {agg['total']} items) — "
            f"prioritise walkthrough of this area at handover."
        )

    bullets.append(
        f"Cumulative exposure this window: {agg['total_downtime_minutes']:.0f} downtime minutes "
        f"and {agg['total_impact_units']:.0f} impacted units."
    )

    unassigned = [r for r in agg["top"] if not r["owner"]]
    if unassigned:
        bullets.append(
            f"{len(unassigned)} of the top risks have no owner — assign before shift close."
        )
    return bullets


def _llm_narrative(shift: str, agg: dict[str, Any]) -> list[str] | None:
    provider = (settings.llm_provider or "none").lower()
    if provider not in ("openai", "azure"):
        return None
    payload_lines = [
        f"Shift: {shift}",
        f"Open risks: {agg['open']} / total {agg['total']}",
        f"Band counts: {agg['by_band']}",
        f"Average score: {agg['avg_score']}, health index: {agg['health']}",
        f"Downtime minutes: {agg['total_downtime_minutes']}, impacted units: {agg['total_impact_units']}",
        "Top risks:",
    ]
    for r in agg["top"]:
        payload_lines.append(
            f"- {r['title']} | area={r['area']} | owner={r['owner'] or 'unassigned'} | "
            f"band={r['band']} score={r['score']} sev={r['severity']} lik={r['likelihood']} | "
            f"action={r['action'] or 'none'} | notes={r['description'][:200]}"
        )
    user_prompt = "\n".join(payload_lines)

    try:
        if provider == "azure":
            if not (settings.azure_openai_endpoint and settings.azure_openai_deployment
                    and settings.openai_api_key):
                return None
            url = (
                f"{settings.azure_openai_endpoint.rstrip('/')}/openai/deployments/"
                f"{settings.azure_openai_deployment}/chat/completions"
                f"?api-version={settings.azure_openai_api_version}"
            )
            headers = {"api-key": settings.openai_api_key}
            body = {"messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ], "temperature": 0.2}
        else:
            if not settings.openai_api_key:
                return None
            url = f"{settings.openai_base_url.rstrip('/')}/chat/completions"
            headers = {"Authorization": f"Bearer {settings.openai_api_key}"}
            body = {"model": settings.openai_model, "temperature": 0.2, "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ]}

        resp = httpx.post(url, json=body, headers=headers, timeout=45)
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"]
        bullets = [ln.lstrip("-• ").strip() for ln in content.splitlines() if ln.strip()]
        return bullets or None
    except Exception as exc:  # noqa: BLE001 - degrade gracefully to rules
        log.warning("LLM summarization failed, falling back to rules: %s", exc)
        return None


FOCUS_TITLE = "Shift Review Focus"


def _hdmx_usdt() -> list[str]:
    """PG12 USDT lines from the HDMX utilisation CSVs, or [] if unavailable.

    Returns [] rather than an error string so the caller can fall back to the
    MMS-parsed figures instead of printing a gap.
    """
    from .config import settings
    from . import metrics

    if not settings.hdmx_enabled:
        return []
    try:
        from .connectors import hdmx
        data = hdmx.usdt(site=metrics.FOCUS_AREA)
        if not data["available"]:
            return []
    except Exception as exc:  # noqa: BLE001 - a share outage must not break the passdown
        log.warning("HDMX USDT unavailable: %s", exc)
        return []

    o = data["overall"]
    lines = [
        f"USDT — {metrics.FOCUS_AREA} {o['usdt_pct']}% unscheduled downtime "
        f"(scheduled {o['sdt_pct']}%, production {o['production_pct']}%) "
        f"across {data['rows']:,} tool-shifts."
    ]

    try:
        by_tool = hdmx.usdt(group_by="Tool", site=metrics.FOCUS_AREA)
        worst_tools = [a for a in by_tool.get("areas", []) if a["usdt_pct"]][:6]
        if worst_tools:
            lines.append(
                f"USDT by tool ({metrics.FOCUS_AREA}) — " + "; ".join(
                    f"{a['area']} {a['usdt_pct']}% ({a['down_hours']}h)"
                    for a in worst_tools
                )
            )
    except Exception as exc:  # noqa: BLE001
        log.warning("HDMX USDT by tool unavailable: %s", exc)

    try:
        from .connectors import hdmx as _h
        trend = _h.usdt_trend(site=metrics.FOCUS_AREA)
        pts = trend.get("points") or []
        if len(pts) >= 2:
            first, last = pts[0], pts[-1]
            direction = "up" if last["usdt_pct"] > first["usdt_pct"] else "down"
            lines.append(
                f"USDT trend ({metrics.FOCUS_AREA}) — {direction} from "
                f"{first['usdt_pct']}% (WW{first['week'][-2:]}) "
                f"to {last['usdt_pct']}% (WW{last['week'][-2:]}) over {len(pts)} weeks."
            )
    except Exception as exc:  # noqa: BLE001
        log.warning("HDMX USDT trend unavailable: %s", exc)

    return lines


def _hsdes_dt_latest() -> list[str]:
    """Repeat-offender tool/cell lines from the HSD-ES DT Latest query, or []."""
    from .config import settings

    if not settings.hsdes_enabled or not settings.hsdes_query_id:
        return []
    try:
        from .connectors import hsdes
        data = hsdes.dt_latest_report()
        if not data["available"]:
            return []
    except Exception as exc:  # noqa: BLE001 - a query outage must not break the passdown
        log.warning("HSD-ES DT Latest unavailable: %s", exc)
        return []

    offenders = data["repeat_offenders"]
    if not offenders:
        return [f"HSD DT Latest — {data['total_records']} record(s), no tool repeated "
                f"{data['min_repeats']}+ times."]

    lines = [
        f"HSD DT Latest — {len(offenders)} tool(s) with {data['min_repeats']}+ repeat DT "
        f"tickets out of {data['total_records']} record(s), needs follow-up:"
    ]
    for o in offenders[:6]:
        prog = f", {'/'.join(o['programs'])}" if o["programs"] else ""
        mod = f" [{o['module']}]" if o["module"] else ""
        lines.append(
            f"  {o['tool']}{mod} — {o['count']}x ({o['open_count']} open{prog}); "
            f"latest {o['latest_open_date'][:10]}"
        )
        if o["repeated_issue"]:
            lines.append(
                f"    🔁 REPEATED ISSUE ({o['repeated_issue_count']}x): {o['repeated_issue']}"
            )
        else:
            lines.append("    (no single issue repeated — each ticket below is a different problem)")
        # Show each ticket's actual problem, not just its repeated title —
        # de-duplicate identical problem text so genuinely-distinct repeat
        # issues on the same asset are still each visible.
        seen: set[str] = set()
        shown = 0
        for issue in o["issues"]:
            key = issue["problem"].lower()
            if key in seen:
                continue
            seen.add(key)
            flag = " (repeated)" if issue["is_repeated_issue"] else ""
            lines.append(
                f"    • [{issue['open_date'][:10]}] {issue['problem']}{flag}"
            )
            shown += 1
            if shown >= 3:
                break
    return lines


def _hdmx_hot_swap() -> list[str]:
    """Hot swap and waiting-for-spare lines from HDMX, or [] if unavailable."""
    from .config import settings

    if not settings.hdmx_enabled:
        return []
    try:
        from .connectors import hdmx
        hs = hdmx.hot_swap_trend()
        ws = hdmx.waiting_for_spare()
    except Exception as exc:  # noqa: BLE001
        log.warning("HDMX hot swap unavailable: %s", exc)
        return []

    lines: list[str] = []
    if hs.get("available"):
        lines.append("Hot swap trend — " + "; ".join(
            f"WW{w['week'][-2:]}: {w['hot_swap']:g} swaps, UDT {w['udt_pct']}%"
            for w in hs["weeks"][-4:]))
        top = [p for p in hs["products"] if p["hot_swap"]][:4]
        if top:
            lines.append("Hot swap by product — " + ", ".join(
                f"{p['product']} {p['hot_swap']:g}" for p in top))

    if ws.get("available"):
        lines.append(
            f"Waiting for spare — {ws['count']} open event(s), {ws['total_hours']}h total "
            f"across {ws['tools_affected']} tool(s); longest: " + "; ".join(
                f"{i['tool']} {i['waiting_hours']}h" for i in ws["items"][:3]))
    elif hs.get("available"):
        lines.append("Waiting for spare — none open in CMMS.")

    return lines


def focus_bullets() -> list[str]:
    """Headline lines for the standing shift-review agenda.

    Order follows how the review is run: LIPAS attainment, then USDT by area,
    hot swap trend, items waiting for spare, conversion, HDMX DT trend, and
    HSD-ES DT Latest repeat-offender follow-up. Every figure is quoted from the
    passdown/live systems; topics with no data say so rather than being
    silently dropped, so a missing section is visible at handover.
    """
    from . import metrics

    out: list[str] = []

    # --- LIPAS ---
    secs = metrics.lipas_report()["sections"]
    lipas_done = False
    for s in secs:
        total = s["grand_total"]
        if not total:
            continue
        vals = ", ".join(f"{k}: {v}" for k, v in total.items())
        below = []
        for p in s["products"]:
            nums = [n for n in (metrics._pct(v) for k, v in p.items() if k != "product")
                    if n is not None]
            if nums and min(nums) < 100:
                below.append(p["product"])
        tail = (f"{len(below)} product(s) below 100% ({', '.join(below[:3])})"
                if below else "all reporting products at 100%")
        out.append(f"LIPAS — {s['section']}: {vals}; {tail}.")
        lipas_done = True
    if not lipas_done:
        out.append("LIPAS — no attainment table loaded; run Sync MMS Passdown.")

    # --- VPO misses ---
    # LIPAS can read 100% while individual VPO queues still miss, so these are
    # reported separately rather than folded into the LIPAS line.
    vpo = metrics.vpo_report()
    if vpo["misses"]:
        detail = "; ".join(
            f"{m['detail']} ("
            + ", ".join(f"{p['product']} {p['qty']}" for p in m["products"]) + ")"
            for m in vpo["misses"][:3]
        )
        out.append(f"VPO miss — {len(vpo['misses'])} entr(y/ies), "
                   f"{vpo['total_miss_qty']} unit(s): {detail}")
    elif vpo.get("templates"):
        out.append(f"VPO miss — {len(vpo['templates'])} heading(s) present but the "
                   "tables are blank; status not stated in the passdown.")

    # --- USDT by area ---
    # Prefer the HDMX utilisation CSVs: those are named columns, so the figures
    # are verbatim rather than parsed out of passdown prose.
    hdmx_usdt = _hdmx_usdt()
    if hdmx_usdt:
        out.extend(hdmx_usdt)
    else:
        usdt = metrics.usdt_by_area()
        if usdt["available"]:
            rate_txt = "; ".join(
                f"{r['period']} " + ", ".join(f"{k} {v}" for k, v in r.items() if k != "period")
                for r in usdt["rates"][:2]
            )
            if rate_txt:
                out.append(f"USDT — {rate_txt}.")
            for a in usdt["areas"][:3]:
                line = f"USDT by area — {a['area']}: {a['detail'][:220]}"
                if a["help_needed"]:
                    line += f" | HELP NEEDED: {a['help_needed'][:160]}"
                out.append(line)
        else:
            out.append("USDT by area — no MEOS section loaded.")

    # --- Hot swap trend + waiting for spare ---
    hdmx_hs = _hdmx_hot_swap()
    if hdmx_hs:
        out.extend(hdmx_hs)
    else:
        hs = metrics.hot_swap_and_spares()
        if hs["available"]:
            if hs["trend"]:
                out.append("Hot swap trend — " + "; ".join(
                    f"{t['week']}: {t['detail'][:120]}" for t in hs["trend"][:4]))
            if hs["waiting"]:
                out.append("Waiting for spare — " + "; ".join(
                    f"{w['item']} ({w['status'] or 'status not stated'})"
                    for w in hs["waiting"][:5]))
            else:
                out.append("Waiting for spare — none listed in the passdown.")
        else:
            out.append("Hot swap / waiting for spare — no collaterals section loaded.")

    # --- Conversion ---
    conv = metrics.conversion_status()
    if conv["available"]:
        mods = ", ".join(f"{m['module']} {m['rate']}" for m in conv["modules"])
        target = f" (target {conv['target']})" if conv["target"] else ""
        misses = [m["module"] for m in conv["modules"]
                  if (metrics._pct(m["rate"]) or 0) < (metrics._pct(conv["target"]) or 95)]
        tail = f"; below target: {', '.join(misses)}" if misses else "; all at or above target"
        out.append(f"Conversion{target} — {mods}{tail}.")
    else:
        out.append("Conversion — no conversion status section loaded.")

    # --- HDMX DT trend ---
    dt = metrics.hdmx_dt_trend()
    if dt["available"]:
        if dt["products"]:
            out.append(f"HDMX DT trend ({metrics.FOCUS_AREA}) — " + "; ".join(
                f"{p['product']}: {p['detail'][:110]}" for p in dt["products"][:4]))
        else:
            out.append(f"HDMX DT trend — no {metrics.FOCUS_AREA} entries this shift.")
        if dt["chillers"]:
            out.append("Chiller status — " + "; ".join(
                f"{c['unit']}: {c['detail'][:130]}" for c in dt["chillers"][:3]))
    else:
        out.append("HDMX DT trend — no DT/chiller section loaded.")

    # --- HSD-ES DT Latest (repeat tool/cell follow-up) ---
    out.extend(_hsdes_dt_latest())

    return out


# Maps a bullet's leading label (before " — ") to the group it belongs to in
# the dashboard table, and the display order of groups. Longer/more specific
# prefixes are matched before shorter ones (e.g. "HSD DT Latest" before a bare
# "HSD"), so this list order matters.
FOCUS_GROUPS: list[tuple[str, str]] = [
    ("LIPAS", "LIPAS Attainment"),
    ("VPO miss", "VPO"),
    ("USDT by tool", "USDT"),
    ("USDT trend", "USDT"),
    ("USDT by area", "USDT"),
    ("USDT", "USDT"),
    ("Hot swap trend", "Hot Swap & Spares"),
    ("Hot swap by product", "Hot Swap & Spares"),
    ("Waiting for spare", "Hot Swap & Spares"),
    ("Conversion", "Conversion"),
    ("HDMX DT trend", "HDMX DT & Chiller"),
    ("Chiller status", "HDMX DT & Chiller"),
    ("HSD DT Latest", "HSD DT Latest (repeat issues)"),
]
GROUP_ORDER = [
    "LIPAS Attainment", "VPO", "USDT", "Hot Swap & Spares",
    "Conversion", "HDMX DT & Chiller", "HSD DT Latest (repeat issues)",
]

# Keyword signals used to colour-code each group's status badge. Checked in
# order; the first list whose keyword is found anywhere in the group's text
# (case-insensitive) wins, so put the most urgent signals first.
_ATTENTION_KEYWORDS = (
    "critical", "repeated issue", "below target", "help needed", "miss",
    "trip", "tripped", "disable", "escalat",
)
_NO_DATA_KEYWORDS = (
    "not configured", "unavailable", "no rows", "not stated",
)
_NO_DATA_RE = re.compile(r"\bno\b.{0,40}\b(loaded|section|table)\b", re.I)


def focus_table() -> list[dict[str, Any]]:
    """Group ``focus_bullets()`` into a table-friendly structure.

    Each row is one agenda topic (LIPAS, VPO, USDT, ...) with a status badge
    (OK / Attention / No data) and its lines nested by indent depth, so the
    dashboard can render the same data the passdown text uses as an actual
    table instead of one long flat bullet list.
    """
    bullets = focus_bullets()

    groups: dict[str, list[dict[str, Any]]] = {name: [] for name in GROUP_ORDER}
    current = GROUP_ORDER[0]
    for line in bullets:
        indent = len(line) - len(line.lstrip(" "))
        stripped = line.strip()
        if indent == 0:
            label = stripped.split(" — ", 1)[0].strip()
            for prefix, group in FOCUS_GROUPS:
                if label.startswith(prefix):
                    current = group
                    break
        groups[current].append({"text": stripped, "depth": indent // 2})

    rows = []
    for name in GROUP_ORDER:
        lines = groups[name]
        if not lines:
            continue
        blob = " ".join(l["text"] for l in lines).lower()
        if any(k in blob for k in _NO_DATA_KEYWORDS) or _NO_DATA_RE.search(blob):
            status = "No data"
        elif any(k in blob for k in _ATTENTION_KEYWORDS):
            status = "Attention"
        else:
            status = "OK"
        rows.append({"group": name, "status": status, "lines": lines})
    return rows


def summarize(shift: str, agg: dict[str, Any]) -> tuple[list[str], str]:
    """Return (bullets, generator_name)."""
    bullets = _llm_narrative(shift, agg)
    if bullets:
        return bullets, (settings.llm_provider or "llm").lower()
    return _rule_narrative(shift, agg), "rules"


BAND_COLORS = {
    "Critical": "#b3261e",
    "High": "#e8710a",
    "Medium": "#c9a227",
    "Low": "#2e7d32",
}


def render_html(shift: str, agg: dict[str, Any], bullets: list[str],
                period_start: datetime, period_end: datetime, generator: str) -> str:
    def esc(v: Any) -> str:
        return html.escape(str(v))

    def title_cell(r: dict[str, Any]) -> str:
        """Link the title back to its origin: the MMS section, or the Outlook mail itself."""
        link = (r.get("source_link") or "").strip()
        label = f"<b>{esc(r['title'])}</b>"
        if link:
            label = (f"<a href=\"{esc(link)}\" style='color:#0f5fd7;text-decoration:none'>"
                     f"{label}</a>")
        origin = esc(r.get("source") or "")
        hint = (f" <span style='color:#8a94a6;font-size:11px'>&#128279; open in {origin}</span>"
                if link and origin else "")
        return label + hint

    rows = "".join(
        f"<tr>"
        f"<td style='padding:6px 10px;border-bottom:1px solid #eee'>"
        f"<span style='display:inline-block;padding:2px 8px;border-radius:10px;color:#fff;"
        f"font-size:11px;background:{BAND_COLORS.get(r['band'], '#666')}'>{esc(r['band'])}</span></td>"
        f"<td style='padding:6px 10px;border-bottom:1px solid #eee'>{title_cell(r)}<br>"
        f"<span style='color:#666;font-size:12px'>{esc(r['description'][:140])}</span></td>"
        f"<td style='padding:6px 10px;border-bottom:1px solid #eee'>{esc(r['area'])}</td>"
        f"<td style='padding:6px 10px;border-bottom:1px solid #eee'>{esc(r['owner'] or '—')}</td>"
        f"<td style='padding:6px 10px;border-bottom:1px solid #eee;text-align:right'>{esc(r['score'])}</td>"
        f"<td style='padding:6px 10px;border-bottom:1px solid #eee'>{esc(r['action'] or '—')}</td>"
        f"</tr>"
        for r in agg["top"]
    ) or "<tr><td colspan='6' style='padding:10px;color:#666'>No risks in this window.</td></tr>"

    bullet_html = "".join(f"<li style='margin-bottom:6px'>{esc(b)}</li>" for b in bullets)
    focus_html = "".join(
        f"<li style='margin-bottom:6px'>{esc(b)}</li>" for b in focus_bullets()
    )
    bands = agg["by_band"]
    chips = "".join(
        f"<span style='display:inline-block;margin-right:8px;padding:4px 10px;border-radius:12px;"
        f"color:#fff;font-size:12px;background:{BAND_COLORS[b]}'>{b}: {bands.get(b, 0)}</span>"
        for b in BAND_COLORS
    )

    return f"""<!doctype html>
<html><body style="margin:0;background:#f4f6f8;font-family:Segoe UI,Arial,sans-serif;color:#1f2933">
<div style="max-width:860px;margin:0 auto;padding:20px">
  <div style="background:#0f2f5f;color:#fff;padding:18px 22px;border-radius:8px 8px 0 0">
    <div style="font-size:20px;font-weight:600">Shift {esc(shift)} Risk Passdown</div>
    <div style="font-size:13px;opacity:.85">
      {esc(period_start.strftime('%Y-%m-%d %H:%M'))} &rarr; {esc(period_end.strftime('%Y-%m-%d %H:%M'))} UTC
      &nbsp;|&nbsp; generated by {esc(generator)} engine
    </div>
  </div>
  <div style="background:#fff;padding:20px 22px;border-radius:0 0 8px 8px">
    <div style="display:block;margin-bottom:14px">
      <span style="font-size:34px;font-weight:700">{esc(agg['health'])}</span>
      <span style="color:#666"> / 100 shift health index</span><br>
      <span style="color:#666;font-size:13px">
        {esc(agg['open'])} open risks &middot; avg score {esc(agg['avg_score'])} &middot;
        {esc(agg['total_downtime_minutes'])} downtime min &middot;
        {esc(agg['total_impact_units'])} units impacted
      </span>
    </div>
    <div style="margin-bottom:18px">{chips}</div>
    <h3 style="margin:0 0 8px;font-size:15px">Executive Summary</h3>
    <ul style="margin:0 0 20px;padding-left:18px;font-size:14px;line-height:1.5">{bullet_html}</ul>
    <h3 style="margin:0 0 8px;font-size:15px">Shift Review Focus</h3>
    <div style="color:#666;font-size:12px;margin-bottom:6px">
      LIPAS &middot; USDT by area &middot; Hot swap trend &middot; Waiting for spare
      &middot; Conversion &middot; HDMX DT trend
    </div>
    <ul style="margin:0 0 20px;padding-left:18px;font-size:13px;line-height:1.5">{focus_html}</ul>
    <h3 style="margin:0 0 8px;font-size:15px">Top Risks</h3>
    <table style="width:100%;border-collapse:collapse;font-size:13px">
      <thead><tr style="background:#f0f3f7;text-align:left">
        <th style="padding:8px 10px">Band</th><th style="padding:8px 10px">Risk</th>
        <th style="padding:8px 10px">Area</th><th style="padding:8px 10px">Owner</th>
        <th style="padding:8px 10px;text-align:right">Score</th><th style="padding:8px 10px">Next Action</th>
      </tr></thead>
      <tbody>{rows}</tbody>
    </table>
    <p style="color:#8a94a6;font-size:11px;margin-top:20px">
      Automated by the Shift Risk Management System. Do not reply to this mailbox.
    </p>
  </div>
</div></body></html>"""


def render_text(shift: str, agg: dict[str, Any], bullets: list[str],
                period_start: datetime, period_end: datetime) -> str:
    lines = [
        f"SHIFT {shift} RISK PASSDOWN",
        f"{period_start:%Y-%m-%d %H:%M} -> {period_end:%Y-%m-%d %H:%M} UTC",
        "",
        f"Health index: {agg['health']}/100 | Open risks: {agg['open']} | Avg score: {agg['avg_score']}",
        f"Bands: " + ", ".join(f"{b}={agg['by_band'].get(b, 0)}" for b in BAND_COLORS),
        "",
        "EXECUTIVE SUMMARY",
    ]
    lines += [f"  - {b}" for b in bullets]
    lines += ["", "SHIFT REVIEW FOCUS"]
    lines += [f"  - {b}" for b in focus_bullets()]
    lines += ["", "TOP RISKS"]
    for r in agg["top"]:
        lines.append(
            f"  [{r['band']}] {r['title']} ({r['area']}, {r['owner'] or 'unassigned'}) "
            f"score={r['score']} action={r['action'] or 'TBD'}"
        )
        if (r.get("source_link") or "").strip():
            lines.append(f"      source: {r['source_link']}")
    if not agg["top"]:
        lines.append("  none")
    return "\n".join(lines)
